
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow {
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action FIleAction;

	private global::Gtk.Action ExitAction;

	private global::Gtk.Action PanelsAction;

	private global::Gtk.Action TurbineAction;

	private global::Gtk.Action FileAction;

	private global::Gtk.Action ExitAction1;

	private global::Gtk.VBox vbox1;

	private global::Gtk.MenuBar menubar1;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Table table1;

	private global::Gtk.Label label10;

	private global::Gtk.Label label11;

	private global::Gtk.Label label12;

	private global::Gtk.Label label13;

	private global::Gtk.Label label2;

	private global::Gtk.Label label3;

	private global::Gtk.Label label4;

	private global::Gtk.Label label5;

	private global::Gtk.Label label6;

	private global::Gtk.Label label7;

	private global::Gtk.Label label8;

	private global::Gtk.Label label9;

	private global::Gtk.VSeparator vseparator1;

	private global::Gtk.VBox vbox4;

	private global::Gtk.Table table3;

	private global::Gtk.Label label1;

	private global::Gtk.Label label14;

	private global::Gtk.Label label15;

	private global::Gtk.Label label16;

	private global::Gtk.Label label17;

	private global::Gtk.Label label18;

	private global::Gtk.VScale vscale1;

	private global::Gtk.VScale vscale2;

	private global::Gtk.VScale vscale3;

	private global::Gtk.VScale vscale4;

	private global::Gtk.VScale vscale5;

	private global::Gtk.VScale vscale6;

	private global::Gtk.VBox vbox3;

	private global::Gtk.HSeparator hseparator1;

	private global::Gtk.Label label24;

	private global::Gtk.HBox hbox2;

	private global::Gtk.RadioButton radiobutton3;

	private global::Gtk.RadioButton radiobutton4;

	private global::Gtk.Label label25;

	private global::Gtk.Label label26;

	private global::Gtk.Table table2;

	private global::Gtk.Button button4;

	private global::Gtk.Button button5;

	private global::Gtk.Button button6;

	private global::Gtk.VSeparator vseparator2;

	private global::Gtk.VBox vbox2;

	private global::Gtk.Label label19;

	private global::Gtk.Table table4;

	private global::Gtk.Label label20;

	private global::Gtk.Label label21;

	private global::Gtk.Label label22;

	private global::Gtk.Label label23;

	private global::Gtk.SpinButton spinbutton1;

	private global::Gtk.SpinButton spinbutton2;

	private global::Gtk.RadioButton radiobutton1;

	private global::Gtk.RadioButton radiobutton2;

	private global::Gtk.ToggleButton togglebutton2;

	private global::Gtk.Statusbar statusbar1;

	protected virtual void Build() {
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.FIleAction = new global::Gtk.Action("FIleAction", global::Mono.Unix.Catalog.GetString("FIle"), null, null);
		this.FIleAction.ShortLabel = global::Mono.Unix.Catalog.GetString("FIle");
		w1.Add(this.FIleAction, null);
		this.ExitAction = new global::Gtk.Action("ExitAction", global::Mono.Unix.Catalog.GetString("Exit"), null, null);
		this.ExitAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Exit");
		w1.Add(this.ExitAction, null);
		this.PanelsAction = new global::Gtk.Action("PanelsAction", global::Mono.Unix.Catalog.GetString("Panels"), null, null);
		this.PanelsAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Panels");
		w1.Add(this.PanelsAction, null);
		this.TurbineAction = new global::Gtk.Action("TurbineAction", global::Mono.Unix.Catalog.GetString("Turbine"), null, null);
		this.TurbineAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Turbine");
		w1.Add(this.TurbineAction, null);
		this.FileAction = new global::Gtk.Action("FileAction", global::Mono.Unix.Catalog.GetString("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("File");
		w1.Add(this.FileAction, null);
		this.ExitAction1 = new global::Gtk.Action("ExitAction1", global::Mono.Unix.Catalog.GetString("Exit"), null, null);
		this.ExitAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Exit");
		w1.Add(this.ExitAction1, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Reactor");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='ExitAction1' action='ExitAction1'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add(this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table(((uint)(7)), ((uint)(2)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.label10 = new global::Gtk.Label();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("no value");
		this.table1.Add(this.label10);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1[this.label10]));
		w3.TopAttach = ((uint)(2));
		w3.BottomAttach = ((uint)(3));
		w3.LeftAttach = ((uint)(1));
		w3.RightAttach = ((uint)(2));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label11 = new global::Gtk.Label();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("no value");
		this.table1.Add(this.label11);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.label11]));
		w4.TopAttach = ((uint)(3));
		w4.BottomAttach = ((uint)(4));
		w4.LeftAttach = ((uint)(1));
		w4.RightAttach = ((uint)(2));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label12 = new global::Gtk.Label();
		this.label12.Name = "label12";
		this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("no value");
		this.table1.Add(this.label12);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.label12]));
		w5.TopAttach = ((uint)(4));
		w5.BottomAttach = ((uint)(5));
		w5.LeftAttach = ((uint)(1));
		w5.RightAttach = ((uint)(2));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label13 = new global::Gtk.Label();
		this.label13.Name = "label13";
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("no value");
		this.table1.Add(this.label13);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.label13]));
		w6.TopAttach = ((uint)(5));
		w6.BottomAttach = ((uint)(6));
		w6.LeftAttach = ((uint)(1));
		w6.RightAttach = ((uint)(2));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Tavg");
		this.table1.Add(this.label2);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1[this.label2]));
		w7.TopAttach = ((uint)(2));
		w7.BottomAttach = ((uint)(3));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("no value");
		this.table1.Add(this.label3);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1[this.label3]));
		w8.LeftAttach = ((uint)(1));
		w8.RightAttach = ((uint)(2));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Tref");
		this.table1.Add(this.label4);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1[this.label4]));
		w9.TopAttach = ((uint)(3));
		w9.BottomAttach = ((uint)(4));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label5 = new global::Gtk.Label();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("no value");
		this.table1.Add(this.label5);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1[this.label5]));
		w10.TopAttach = ((uint)(1));
		w10.BottomAttach = ((uint)(2));
		w10.LeftAttach = ((uint)(1));
		w10.RightAttach = ((uint)(2));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label6 = new global::Gtk.Label();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Turbine power");
		this.table1.Add(this.label6);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1[this.label6]));
		w11.TopAttach = ((uint)(5));
		w11.BottomAttach = ((uint)(6));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label7 = new global::Gtk.Label();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Neutron flux");
		this.table1.Add(this.label7);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1[this.label7]));
		w12.TopAttach = ((uint)(4));
		w12.BottomAttach = ((uint)(5));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label8 = new global::Gtk.Label();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Boron concentration");
		this.table1.Add(this.label8);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1[this.label8]));
		w13.TopAttach = ((uint)(1));
		w13.BottomAttach = ((uint)(2));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label9 = new global::Gtk.Label();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Burnup");
		this.table1.Add(this.label9);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1[this.label9]));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		this.hbox1.Add(this.table1);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.table1]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vseparator1 = new global::Gtk.VSeparator();
		this.vseparator1.Name = "vseparator1";
		this.hbox1.Add(this.vseparator1);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vseparator1]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.table3 = new global::Gtk.Table(((uint)(2)), ((uint)(6)), false);
		this.table3.Name = "table3";
		this.table3.RowSpacing = ((uint)(6));
		this.table3.ColumnSpacing = ((uint)(6));
		// Container child table3.Gtk.Table+TableChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Group B");
		this.table3.Add(this.label1);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table3[this.label1]));
		w17.LeftAttach = ((uint)(1));
		w17.RightAttach = ((uint)(2));
		w17.XOptions = ((global::Gtk.AttachOptions)(4));
		w17.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label14 = new global::Gtk.Label();
		this.label14.Name = "label14";
		this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("Group A");
		this.table3.Add(this.label14);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table3[this.label14]));
		w18.XOptions = ((global::Gtk.AttachOptions)(4));
		w18.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label15 = new global::Gtk.Label();
		this.label15.Name = "label15";
		this.label15.LabelProp = global::Mono.Unix.Catalog.GetString("Group C");
		this.table3.Add(this.label15);
		global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table3[this.label15]));
		w19.LeftAttach = ((uint)(2));
		w19.RightAttach = ((uint)(3));
		w19.XOptions = ((global::Gtk.AttachOptions)(4));
		w19.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label16 = new global::Gtk.Label();
		this.label16.Name = "label16";
		this.label16.LabelProp = global::Mono.Unix.Catalog.GetString("Group D");
		this.table3.Add(this.label16);
		global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table3[this.label16]));
		w20.LeftAttach = ((uint)(3));
		w20.RightAttach = ((uint)(4));
		w20.XOptions = ((global::Gtk.AttachOptions)(4));
		w20.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label17 = new global::Gtk.Label();
		this.label17.Name = "label17";
		this.label17.LabelProp = global::Mono.Unix.Catalog.GetString("Group SA");
		this.table3.Add(this.label17);
		global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table3[this.label17]));
		w21.LeftAttach = ((uint)(4));
		w21.RightAttach = ((uint)(5));
		w21.XOptions = ((global::Gtk.AttachOptions)(4));
		w21.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label18 = new global::Gtk.Label();
		this.label18.Name = "label18";
		this.label18.LabelProp = global::Mono.Unix.Catalog.GetString("Group SB");
		this.table3.Add(this.label18);
		global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table3[this.label18]));
		w22.LeftAttach = ((uint)(5));
		w22.RightAttach = ((uint)(6));
		w22.XOptions = ((global::Gtk.AttachOptions)(4));
		w22.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.vscale1 = new global::Gtk.VScale(null);
		this.vscale1.CanFocus = true;
		this.vscale1.Name = "vscale1";
		this.vscale1.Inverted = true;
		this.vscale1.Adjustment.Upper = 228;
		this.vscale1.Adjustment.PageIncrement = 10;
		this.vscale1.Adjustment.StepIncrement = 1;
		this.vscale1.DrawValue = true;
		this.vscale1.Digits = 0;
		this.vscale1.ValuePos = ((global::Gtk.PositionType)(3));
		this.table3.Add(this.vscale1);
		global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table3[this.vscale1]));
		w23.TopAttach = ((uint)(1));
		w23.BottomAttach = ((uint)(2));
		w23.XOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.vscale2 = new global::Gtk.VScale(null);
		this.vscale2.CanFocus = true;
		this.vscale2.Name = "vscale2";
		this.vscale2.Inverted = true;
		this.vscale2.Adjustment.Upper = 228;
		this.vscale2.Adjustment.PageIncrement = 10;
		this.vscale2.Adjustment.StepIncrement = 1;
		this.vscale2.DrawValue = true;
		this.vscale2.Digits = 0;
		this.vscale2.ValuePos = ((global::Gtk.PositionType)(3));
		this.table3.Add(this.vscale2);
		global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table3[this.vscale2]));
		w24.TopAttach = ((uint)(1));
		w24.BottomAttach = ((uint)(2));
		w24.LeftAttach = ((uint)(1));
		w24.RightAttach = ((uint)(2));
		w24.XOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.vscale3 = new global::Gtk.VScale(null);
		this.vscale3.CanFocus = true;
		this.vscale3.Name = "vscale3";
		this.vscale3.Inverted = true;
		this.vscale3.Adjustment.Upper = 228;
		this.vscale3.Adjustment.PageIncrement = 10;
		this.vscale3.Adjustment.StepIncrement = 1;
		this.vscale3.DrawValue = true;
		this.vscale3.Digits = 0;
		this.vscale3.ValuePos = ((global::Gtk.PositionType)(3));
		this.table3.Add(this.vscale3);
		global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table3[this.vscale3]));
		w25.TopAttach = ((uint)(1));
		w25.BottomAttach = ((uint)(2));
		w25.LeftAttach = ((uint)(2));
		w25.RightAttach = ((uint)(3));
		w25.XOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.vscale4 = new global::Gtk.VScale(null);
		this.vscale4.CanFocus = true;
		this.vscale4.Name = "vscale4";
		this.vscale4.Inverted = true;
		this.vscale4.Adjustment.Upper = 228;
		this.vscale4.Adjustment.PageIncrement = 10;
		this.vscale4.Adjustment.StepIncrement = 1;
		this.vscale4.DrawValue = true;
		this.vscale4.Digits = 0;
		this.vscale4.ValuePos = ((global::Gtk.PositionType)(3));
		this.table3.Add(this.vscale4);
		global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table3[this.vscale4]));
		w26.TopAttach = ((uint)(1));
		w26.BottomAttach = ((uint)(2));
		w26.LeftAttach = ((uint)(3));
		w26.RightAttach = ((uint)(4));
		w26.XOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.vscale5 = new global::Gtk.VScale(null);
		this.vscale5.CanFocus = true;
		this.vscale5.Name = "vscale5";
		this.vscale5.Inverted = true;
		this.vscale5.Adjustment.Upper = 228;
		this.vscale5.Adjustment.PageIncrement = 10;
		this.vscale5.Adjustment.StepIncrement = 1;
		this.vscale5.DrawValue = true;
		this.vscale5.Digits = 0;
		this.vscale5.ValuePos = ((global::Gtk.PositionType)(3));
		this.table3.Add(this.vscale5);
		global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table3[this.vscale5]));
		w27.TopAttach = ((uint)(1));
		w27.BottomAttach = ((uint)(2));
		w27.LeftAttach = ((uint)(4));
		w27.RightAttach = ((uint)(5));
		w27.XOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.vscale6 = new global::Gtk.VScale(null);
		this.vscale6.CanFocus = true;
		this.vscale6.Name = "vscale6";
		this.vscale6.Inverted = true;
		this.vscale6.Adjustment.Upper = 228;
		this.vscale6.Adjustment.PageIncrement = 10;
		this.vscale6.Adjustment.StepIncrement = 1;
		this.vscale6.DrawValue = true;
		this.vscale6.Digits = 0;
		this.vscale6.ValuePos = ((global::Gtk.PositionType)(3));
		this.table3.Add(this.vscale6);
		global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table3[this.vscale6]));
		w28.TopAttach = ((uint)(1));
		w28.BottomAttach = ((uint)(2));
		w28.LeftAttach = ((uint)(5));
		w28.RightAttach = ((uint)(6));
		w28.XOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox4.Add(this.table3);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.table3]));
		w29.Position = 0;
		// Container child vbox4.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hseparator1 = new global::Gtk.HSeparator();
		this.hseparator1.Name = "hseparator1";
		this.vbox3.Add(this.hseparator1);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hseparator1]));
		w30.Position = 0;
		w30.Expand = false;
		w30.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.label24 = new global::Gtk.Label();
		this.label24.Name = "label24";
		this.label24.LabelProp = global::Mono.Unix.Catalog.GetString("Rod control");
		this.vbox3.Add(this.label24);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label24]));
		w31.Position = 1;
		w31.Expand = false;
		w31.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.radiobutton3 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Auto"));
		this.radiobutton3.CanFocus = true;
		this.radiobutton3.Name = "radiobutton3";
		this.radiobutton3.Active = true;
		this.radiobutton3.DrawIndicator = true;
		this.radiobutton3.UseUnderline = true;
		this.radiobutton3.Group = new global::GLib.SList(global::System.IntPtr.Zero);
		this.hbox2.Add(this.radiobutton3);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.radiobutton3]));
		w32.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.radiobutton4 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Manual"));
		this.radiobutton4.CanFocus = true;
		this.radiobutton4.Name = "radiobutton4";
		this.radiobutton4.DrawIndicator = true;
		this.radiobutton4.UseUnderline = true;
		this.radiobutton4.Group = this.radiobutton3.Group;
		this.hbox2.Add(this.radiobutton4);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.radiobutton4]));
		w33.Position = 1;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label25 = new global::Gtk.Label();
		this.label25.Name = "label25";
		this.label25.LabelProp = global::Mono.Unix.Catalog.GetString("Speed: ");
		this.hbox2.Add(this.label25);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label25]));
		w34.Position = 2;
		w34.Expand = false;
		w34.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label26 = new global::Gtk.Label();
		this.label26.Name = "label26";
		this.label26.LabelProp = global::Mono.Unix.Catalog.GetString("no value");
		this.hbox2.Add(this.label26);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label26]));
		w35.Position = 3;
		w35.Expand = false;
		w35.Fill = false;
		this.vbox3.Add(this.hbox2);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox2]));
		w36.Position = 2;
		w36.Expand = false;
		w36.Fill = false;
		this.vbox4.Add(this.vbox3);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.vbox3]));
		w37.Position = 1;
		w37.Expand = false;
		w37.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.table2 = new global::Gtk.Table(((uint)(2)), ((uint)(3)), false);
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(6));
		this.table2.ColumnSpacing = ((uint)(6));
		// Container child table2.Gtk.Table+TableChild
		this.button4 = new global::Gtk.Button();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString("STEP UP");
		this.table2.Add(this.button4);
		global::Gtk.Table.TableChild w38 = ((global::Gtk.Table.TableChild)(this.table2[this.button4]));
		w38.XOptions = ((global::Gtk.AttachOptions)(4));
		w38.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.button5 = new global::Gtk.Button();
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString("STEP DOWN");
		this.table2.Add(this.button5);
		global::Gtk.Table.TableChild w39 = ((global::Gtk.Table.TableChild)(this.table2[this.button5]));
		w39.TopAttach = ((uint)(1));
		w39.BottomAttach = ((uint)(2));
		w39.XOptions = ((global::Gtk.AttachOptions)(4));
		w39.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.button6 = new global::Gtk.Button();
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.button6.Label = global::Mono.Unix.Catalog.GetString("TRIP");
		this.table2.Add(this.button6);
		global::Gtk.Table.TableChild w40 = ((global::Gtk.Table.TableChild)(this.table2[this.button6]));
		w40.TopAttach = ((uint)(1));
		w40.BottomAttach = ((uint)(2));
		w40.LeftAttach = ((uint)(2));
		w40.RightAttach = ((uint)(3));
		w40.XOptions = ((global::Gtk.AttachOptions)(4));
		w40.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox4.Add(this.table2);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.table2]));
		w41.Position = 2;
		w41.Expand = false;
		w41.Fill = false;
		this.hbox1.Add(this.vbox4);
		global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox4]));
		w42.Position = 2;
		w42.Expand = false;
		w42.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vseparator2 = new global::Gtk.VSeparator();
		this.vseparator2.Name = "vseparator2";
		this.hbox1.Add(this.vseparator2);
		global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vseparator2]));
		w43.Position = 3;
		w43.Expand = false;
		w43.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.label19 = new global::Gtk.Label();
		this.label19.Name = "label19";
		this.label19.LabelProp = global::Mono.Unix.Catalog.GetString("RCS makeup");
		this.vbox2.Add(this.label19);
		global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label19]));
		w44.Position = 0;
		w44.Expand = false;
		w44.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.table4 = new global::Gtk.Table(((uint)(2)), ((uint)(3)), false);
		this.table4.Name = "table4";
		this.table4.RowSpacing = ((uint)(6));
		this.table4.ColumnSpacing = ((uint)(6));
		// Container child table4.Gtk.Table+TableChild
		this.label20 = new global::Gtk.Label();
		this.label20.Name = "label20";
		this.label20.LabelProp = global::Mono.Unix.Catalog.GetString("Water");
		this.table4.Add(this.label20);
		global::Gtk.Table.TableChild w45 = ((global::Gtk.Table.TableChild)(this.table4[this.label20]));
		w45.TopAttach = ((uint)(1));
		w45.BottomAttach = ((uint)(2));
		w45.XOptions = ((global::Gtk.AttachOptions)(4));
		w45.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.label21 = new global::Gtk.Label();
		this.label21.Name = "label21";
		this.label21.LabelProp = global::Mono.Unix.Catalog.GetString("liters");
		this.table4.Add(this.label21);
		global::Gtk.Table.TableChild w46 = ((global::Gtk.Table.TableChild)(this.table4[this.label21]));
		w46.LeftAttach = ((uint)(2));
		w46.RightAttach = ((uint)(3));
		w46.XOptions = ((global::Gtk.AttachOptions)(4));
		w46.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.label22 = new global::Gtk.Label();
		this.label22.Name = "label22";
		this.label22.LabelProp = global::Mono.Unix.Catalog.GetString("Boron");
		this.table4.Add(this.label22);
		global::Gtk.Table.TableChild w47 = ((global::Gtk.Table.TableChild)(this.table4[this.label22]));
		w47.XOptions = ((global::Gtk.AttachOptions)(4));
		w47.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.label23 = new global::Gtk.Label();
		this.label23.Name = "label23";
		this.label23.LabelProp = global::Mono.Unix.Catalog.GetString("liters");
		this.table4.Add(this.label23);
		global::Gtk.Table.TableChild w48 = ((global::Gtk.Table.TableChild)(this.table4[this.label23]));
		w48.TopAttach = ((uint)(1));
		w48.BottomAttach = ((uint)(2));
		w48.LeftAttach = ((uint)(2));
		w48.RightAttach = ((uint)(3));
		w48.XOptions = ((global::Gtk.AttachOptions)(4));
		w48.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.spinbutton1 = new global::Gtk.SpinButton(0, 1000, 1);
		this.spinbutton1.CanFocus = true;
		this.spinbutton1.Name = "spinbutton1";
		this.spinbutton1.Adjustment.PageIncrement = 10;
		this.spinbutton1.ClimbRate = 1;
		this.spinbutton1.Numeric = true;
		this.table4.Add(this.spinbutton1);
		global::Gtk.Table.TableChild w49 = ((global::Gtk.Table.TableChild)(this.table4[this.spinbutton1]));
		w49.LeftAttach = ((uint)(1));
		w49.RightAttach = ((uint)(2));
		w49.XOptions = ((global::Gtk.AttachOptions)(4));
		w49.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.spinbutton2 = new global::Gtk.SpinButton(0, 1000, 1);
		this.spinbutton2.CanFocus = true;
		this.spinbutton2.Name = "spinbutton2";
		this.spinbutton2.Adjustment.PageIncrement = 10;
		this.spinbutton2.ClimbRate = 1;
		this.spinbutton2.Numeric = true;
		this.table4.Add(this.spinbutton2);
		global::Gtk.Table.TableChild w50 = ((global::Gtk.Table.TableChild)(this.table4[this.spinbutton2]));
		w50.TopAttach = ((uint)(1));
		w50.BottomAttach = ((uint)(2));
		w50.LeftAttach = ((uint)(1));
		w50.RightAttach = ((uint)(2));
		w50.XOptions = ((global::Gtk.AttachOptions)(4));
		w50.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox2.Add(this.table4);
		global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.table4]));
		w51.Position = 1;
		w51.Expand = false;
		w51.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.radiobutton1 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Borate"));
		this.radiobutton1.CanFocus = true;
		this.radiobutton1.Name = "radiobutton1";
		this.radiobutton1.Active = true;
		this.radiobutton1.DrawIndicator = true;
		this.radiobutton1.UseUnderline = true;
		this.radiobutton1.Group = new global::GLib.SList(global::System.IntPtr.Zero);
		this.vbox2.Add(this.radiobutton1);
		global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.radiobutton1]));
		w52.Position = 2;
		w52.Expand = false;
		w52.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.radiobutton2 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Dilute"));
		this.radiobutton2.CanFocus = true;
		this.radiobutton2.Name = "radiobutton2";
		this.radiobutton2.DrawIndicator = true;
		this.radiobutton2.UseUnderline = true;
		this.radiobutton2.Group = this.radiobutton1.Group;
		this.vbox2.Add(this.radiobutton2);
		global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.radiobutton2]));
		w53.Position = 3;
		w53.Expand = false;
		w53.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.togglebutton2 = new global::Gtk.ToggleButton();
		this.togglebutton2.CanFocus = true;
		this.togglebutton2.Name = "togglebutton2";
		this.togglebutton2.UseUnderline = true;
		this.togglebutton2.Label = global::Mono.Unix.Catalog.GetString("START");
		this.vbox2.Add(this.togglebutton2);
		global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.togglebutton2]));
		w54.Position = 4;
		w54.Expand = false;
		w54.Fill = false;
		this.hbox1.Add(this.vbox2);
		global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
		w55.Position = 4;
		w55.Expand = false;
		w55.Fill = false;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w56.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		this.vbox1.Add(this.statusbar1);
		global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.statusbar1]));
		w57.Position = 2;
		w57.Expand = false;
		w57.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll();
		}
		this.DefaultWidth = 735;
		this.DefaultHeight = 409;
		this.Show();
		this.ExitAction.Activated += new global::System.EventHandler(this.OnExitActionActivated);
		this.radiobutton3.Activated += new global::System.EventHandler(this.OnRadiobutton3Activated);
		this.radiobutton4.Activated += new global::System.EventHandler(this.OnRadiobutton4Activated);
		this.button5.Clicked += new global::System.EventHandler(this.OnButton5Clicked);
		this.button4.Clicked += new global::System.EventHandler(this.OnButton4Clicked);
		this.togglebutton2.Clicked += new global::System.EventHandler(this.OnTogglebutton2Clicked);
	}
}
