// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.UIManager UIManager;
    
    private Gtk.Action FIleAction;
    
    private Gtk.Action ExitAction;
    
    private Gtk.Action PanelsAction;
    
    private Gtk.Action TurbineAction;
    
    private Gtk.Action FileAction;
    
    private Gtk.Action ExitAction1;
    
    private Gtk.VBox vbox1;
    
    private Gtk.MenuBar menubar1;
    
    private Gtk.HBox hbox1;
    
    private Gtk.Table table1;
    
    private Gtk.Label label10;
    
    private Gtk.Label label11;
    
    private Gtk.Label label12;
    
    private Gtk.Label label13;
    
    private Gtk.Label label2;
    
    private Gtk.Label label3;
    
    private Gtk.Label label4;
    
    private Gtk.Label label5;
    
    private Gtk.Label label6;
    
    private Gtk.Label label7;
    
    private Gtk.Label label8;
    
    private Gtk.Label label9;
    
    private Gtk.VSeparator vseparator1;
    
    private Gtk.VBox vbox4;
    
    private Gtk.Table table3;
    
    private Gtk.Label label1;
    
    private Gtk.Label label14;
    
    private Gtk.Label label15;
    
    private Gtk.Label label16;
    
    private Gtk.Label label17;
    
    private Gtk.Label label18;
    
    private Gtk.VScale vscale1;
    
    private Gtk.VScale vscale2;
    
    private Gtk.VScale vscale3;
    
    private Gtk.VScale vscale4;
    
    private Gtk.VScale vscale5;
    
    private Gtk.VScale vscale6;
    
    private Gtk.Table table2;
    
    private Gtk.Button button4;
    
    private Gtk.Button button5;
    
    private Gtk.Button button6;
    
    private Gtk.VSeparator vseparator2;
    
    private Gtk.VBox vbox2;
    
    private Gtk.Label label19;
    
    private Gtk.Table table4;
    
    private Gtk.Label label20;
    
    private Gtk.Label label21;
    
    private Gtk.Label label22;
    
    private Gtk.Label label23;
    
    private Gtk.SpinButton spinbutton1;
    
    private Gtk.SpinButton spinbutton2;
    
    private Gtk.RadioButton radiobutton1;
    
    private Gtk.RadioButton radiobutton2;
    
    private Gtk.ToggleButton togglebutton2;
    
    private Gtk.Statusbar statusbar1;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.UIManager = new Gtk.UIManager();
        Gtk.ActionGroup w1 = new Gtk.ActionGroup("Default");
        this.FIleAction = new Gtk.Action("FIleAction", Mono.Unix.Catalog.GetString("FIle"), null, null);
        this.FIleAction.ShortLabel = Mono.Unix.Catalog.GetString("FIle");
        w1.Add(this.FIleAction, null);
        this.ExitAction = new Gtk.Action("ExitAction", Mono.Unix.Catalog.GetString("Exit"), null, null);
        this.ExitAction.ShortLabel = Mono.Unix.Catalog.GetString("Exit");
        w1.Add(this.ExitAction, null);
        this.PanelsAction = new Gtk.Action("PanelsAction", Mono.Unix.Catalog.GetString("Panels"), null, null);
        this.PanelsAction.ShortLabel = Mono.Unix.Catalog.GetString("Panels");
        w1.Add(this.PanelsAction, null);
        this.TurbineAction = new Gtk.Action("TurbineAction", Mono.Unix.Catalog.GetString("Turbine"), null, null);
        this.TurbineAction.ShortLabel = Mono.Unix.Catalog.GetString("Turbine");
        w1.Add(this.TurbineAction, null);
        this.FileAction = new Gtk.Action("FileAction", Mono.Unix.Catalog.GetString("File"), null, null);
        this.FileAction.ShortLabel = Mono.Unix.Catalog.GetString("File");
        w1.Add(this.FileAction, null);
        this.ExitAction1 = new Gtk.Action("ExitAction1", Mono.Unix.Catalog.GetString("Exit"), null, null);
        this.ExitAction1.ShortLabel = Mono.Unix.Catalog.GetString("Exit");
        w1.Add(this.ExitAction1, null);
        this.UIManager.InsertActionGroup(w1, 0);
        this.AddAccelGroup(this.UIManager.AccelGroup);
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("Reactor");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox1 = new Gtk.VBox();
        this.vbox1.Name = "vbox1";
        this.vbox1.Spacing = 6;
        // Container child vbox1.Gtk.Box+BoxChild
        this.UIManager.AddUiFromString("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='ExitAction1' action='ExitAction1'/></menu></menubar></ui>");
        this.menubar1 = ((Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
        this.menubar1.Name = "menubar1";
        this.vbox1.Add(this.menubar1);
        Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
        w2.Position = 0;
        w2.Expand = false;
        w2.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox1 = new Gtk.HBox();
        this.hbox1.Name = "hbox1";
        this.hbox1.Spacing = 6;
        // Container child hbox1.Gtk.Box+BoxChild
        this.table1 = new Gtk.Table(((uint)(7)), ((uint)(2)), false);
        this.table1.Name = "table1";
        this.table1.RowSpacing = ((uint)(6));
        this.table1.ColumnSpacing = ((uint)(6));
        // Container child table1.Gtk.Table+TableChild
        this.label10 = new Gtk.Label();
        this.label10.Name = "label10";
        this.label10.LabelProp = Mono.Unix.Catalog.GetString("no value");
        this.table1.Add(this.label10);
        Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table1[this.label10]));
        w3.TopAttach = ((uint)(2));
        w3.BottomAttach = ((uint)(3));
        w3.LeftAttach = ((uint)(1));
        w3.RightAttach = ((uint)(2));
        w3.XOptions = ((Gtk.AttachOptions)(4));
        w3.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.label11 = new Gtk.Label();
        this.label11.Name = "label11";
        this.label11.LabelProp = Mono.Unix.Catalog.GetString("no value");
        this.table1.Add(this.label11);
        Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table1[this.label11]));
        w4.TopAttach = ((uint)(3));
        w4.BottomAttach = ((uint)(4));
        w4.LeftAttach = ((uint)(1));
        w4.RightAttach = ((uint)(2));
        w4.XOptions = ((Gtk.AttachOptions)(4));
        w4.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.label12 = new Gtk.Label();
        this.label12.Name = "label12";
        this.label12.LabelProp = Mono.Unix.Catalog.GetString("no value");
        this.table1.Add(this.label12);
        Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table1[this.label12]));
        w5.TopAttach = ((uint)(4));
        w5.BottomAttach = ((uint)(5));
        w5.LeftAttach = ((uint)(1));
        w5.RightAttach = ((uint)(2));
        w5.XOptions = ((Gtk.AttachOptions)(4));
        w5.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.label13 = new Gtk.Label();
        this.label13.Name = "label13";
        this.label13.LabelProp = Mono.Unix.Catalog.GetString("no value");
        this.table1.Add(this.label13);
        Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.table1[this.label13]));
        w6.TopAttach = ((uint)(5));
        w6.BottomAttach = ((uint)(6));
        w6.LeftAttach = ((uint)(1));
        w6.RightAttach = ((uint)(2));
        w6.XOptions = ((Gtk.AttachOptions)(4));
        w6.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.label2 = new Gtk.Label();
        this.label2.Name = "label2";
        this.label2.LabelProp = Mono.Unix.Catalog.GetString("Tavg");
        this.table1.Add(this.label2);
        Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.table1[this.label2]));
        w7.TopAttach = ((uint)(2));
        w7.BottomAttach = ((uint)(3));
        w7.XOptions = ((Gtk.AttachOptions)(4));
        w7.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.label3 = new Gtk.Label();
        this.label3.Name = "label3";
        this.label3.LabelProp = Mono.Unix.Catalog.GetString("no value");
        this.table1.Add(this.label3);
        Gtk.Table.TableChild w8 = ((Gtk.Table.TableChild)(this.table1[this.label3]));
        w8.LeftAttach = ((uint)(1));
        w8.RightAttach = ((uint)(2));
        w8.XOptions = ((Gtk.AttachOptions)(4));
        w8.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.label4 = new Gtk.Label();
        this.label4.Name = "label4";
        this.label4.LabelProp = Mono.Unix.Catalog.GetString("Tref");
        this.table1.Add(this.label4);
        Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.table1[this.label4]));
        w9.TopAttach = ((uint)(3));
        w9.BottomAttach = ((uint)(4));
        w9.XOptions = ((Gtk.AttachOptions)(4));
        w9.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.label5 = new Gtk.Label();
        this.label5.Name = "label5";
        this.label5.LabelProp = Mono.Unix.Catalog.GetString("no value");
        this.table1.Add(this.label5);
        Gtk.Table.TableChild w10 = ((Gtk.Table.TableChild)(this.table1[this.label5]));
        w10.TopAttach = ((uint)(1));
        w10.BottomAttach = ((uint)(2));
        w10.LeftAttach = ((uint)(1));
        w10.RightAttach = ((uint)(2));
        w10.XOptions = ((Gtk.AttachOptions)(4));
        w10.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.label6 = new Gtk.Label();
        this.label6.Name = "label6";
        this.label6.LabelProp = Mono.Unix.Catalog.GetString("Turbine power");
        this.table1.Add(this.label6);
        Gtk.Table.TableChild w11 = ((Gtk.Table.TableChild)(this.table1[this.label6]));
        w11.TopAttach = ((uint)(5));
        w11.BottomAttach = ((uint)(6));
        w11.XOptions = ((Gtk.AttachOptions)(4));
        w11.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.label7 = new Gtk.Label();
        this.label7.Name = "label7";
        this.label7.LabelProp = Mono.Unix.Catalog.GetString("Neutron flux");
        this.table1.Add(this.label7);
        Gtk.Table.TableChild w12 = ((Gtk.Table.TableChild)(this.table1[this.label7]));
        w12.TopAttach = ((uint)(4));
        w12.BottomAttach = ((uint)(5));
        w12.XOptions = ((Gtk.AttachOptions)(4));
        w12.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.label8 = new Gtk.Label();
        this.label8.Name = "label8";
        this.label8.LabelProp = Mono.Unix.Catalog.GetString("Boron concentration");
        this.table1.Add(this.label8);
        Gtk.Table.TableChild w13 = ((Gtk.Table.TableChild)(this.table1[this.label8]));
        w13.TopAttach = ((uint)(1));
        w13.BottomAttach = ((uint)(2));
        w13.XOptions = ((Gtk.AttachOptions)(4));
        w13.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.label9 = new Gtk.Label();
        this.label9.Name = "label9";
        this.label9.LabelProp = Mono.Unix.Catalog.GetString("Burnup");
        this.table1.Add(this.label9);
        Gtk.Table.TableChild w14 = ((Gtk.Table.TableChild)(this.table1[this.label9]));
        w14.XOptions = ((Gtk.AttachOptions)(4));
        w14.YOptions = ((Gtk.AttachOptions)(4));
        this.hbox1.Add(this.table1);
        Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.hbox1[this.table1]));
        w15.Position = 0;
        w15.Expand = false;
        w15.Fill = false;
        // Container child hbox1.Gtk.Box+BoxChild
        this.vseparator1 = new Gtk.VSeparator();
        this.vseparator1.Name = "vseparator1";
        this.hbox1.Add(this.vseparator1);
        Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.hbox1[this.vseparator1]));
        w16.Position = 1;
        w16.Expand = false;
        w16.Fill = false;
        // Container child hbox1.Gtk.Box+BoxChild
        this.vbox4 = new Gtk.VBox();
        this.vbox4.Name = "vbox4";
        this.vbox4.Spacing = 6;
        // Container child vbox4.Gtk.Box+BoxChild
        this.table3 = new Gtk.Table(((uint)(2)), ((uint)(6)), false);
        this.table3.Name = "table3";
        this.table3.RowSpacing = ((uint)(6));
        this.table3.ColumnSpacing = ((uint)(6));
        // Container child table3.Gtk.Table+TableChild
        this.label1 = new Gtk.Label();
        this.label1.Name = "label1";
        this.label1.LabelProp = Mono.Unix.Catalog.GetString("Group B");
        this.table3.Add(this.label1);
        Gtk.Table.TableChild w17 = ((Gtk.Table.TableChild)(this.table3[this.label1]));
        w17.LeftAttach = ((uint)(1));
        w17.RightAttach = ((uint)(2));
        w17.XOptions = ((Gtk.AttachOptions)(4));
        w17.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table3.Gtk.Table+TableChild
        this.label14 = new Gtk.Label();
        this.label14.Name = "label14";
        this.label14.LabelProp = Mono.Unix.Catalog.GetString("Group A");
        this.table3.Add(this.label14);
        Gtk.Table.TableChild w18 = ((Gtk.Table.TableChild)(this.table3[this.label14]));
        w18.XOptions = ((Gtk.AttachOptions)(4));
        w18.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table3.Gtk.Table+TableChild
        this.label15 = new Gtk.Label();
        this.label15.Name = "label15";
        this.label15.LabelProp = Mono.Unix.Catalog.GetString("Group C");
        this.table3.Add(this.label15);
        Gtk.Table.TableChild w19 = ((Gtk.Table.TableChild)(this.table3[this.label15]));
        w19.LeftAttach = ((uint)(2));
        w19.RightAttach = ((uint)(3));
        w19.XOptions = ((Gtk.AttachOptions)(4));
        w19.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table3.Gtk.Table+TableChild
        this.label16 = new Gtk.Label();
        this.label16.Name = "label16";
        this.label16.LabelProp = Mono.Unix.Catalog.GetString("Group D");
        this.table3.Add(this.label16);
        Gtk.Table.TableChild w20 = ((Gtk.Table.TableChild)(this.table3[this.label16]));
        w20.LeftAttach = ((uint)(3));
        w20.RightAttach = ((uint)(4));
        w20.XOptions = ((Gtk.AttachOptions)(4));
        w20.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table3.Gtk.Table+TableChild
        this.label17 = new Gtk.Label();
        this.label17.Name = "label17";
        this.label17.LabelProp = Mono.Unix.Catalog.GetString("Group SA");
        this.table3.Add(this.label17);
        Gtk.Table.TableChild w21 = ((Gtk.Table.TableChild)(this.table3[this.label17]));
        w21.LeftAttach = ((uint)(4));
        w21.RightAttach = ((uint)(5));
        w21.XOptions = ((Gtk.AttachOptions)(4));
        w21.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table3.Gtk.Table+TableChild
        this.label18 = new Gtk.Label();
        this.label18.Name = "label18";
        this.label18.LabelProp = Mono.Unix.Catalog.GetString("Group SB");
        this.table3.Add(this.label18);
        Gtk.Table.TableChild w22 = ((Gtk.Table.TableChild)(this.table3[this.label18]));
        w22.LeftAttach = ((uint)(5));
        w22.RightAttach = ((uint)(6));
        w22.XOptions = ((Gtk.AttachOptions)(4));
        w22.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table3.Gtk.Table+TableChild
        this.vscale1 = new Gtk.VScale(null);
        this.vscale1.CanFocus = true;
        this.vscale1.Name = "vscale1";
        this.vscale1.Inverted = true;
        this.vscale1.Adjustment.Upper = 228;
        this.vscale1.Adjustment.PageIncrement = 10;
        this.vscale1.Adjustment.StepIncrement = 1;
        this.vscale1.DrawValue = true;
        this.vscale1.Digits = 0;
        this.vscale1.ValuePos = ((Gtk.PositionType)(3));
        this.table3.Add(this.vscale1);
        Gtk.Table.TableChild w23 = ((Gtk.Table.TableChild)(this.table3[this.vscale1]));
        w23.TopAttach = ((uint)(1));
        w23.BottomAttach = ((uint)(2));
        w23.XOptions = ((Gtk.AttachOptions)(4));
        // Container child table3.Gtk.Table+TableChild
        this.vscale2 = new Gtk.VScale(null);
        this.vscale2.CanFocus = true;
        this.vscale2.Name = "vscale2";
        this.vscale2.Inverted = true;
        this.vscale2.Adjustment.Upper = 228;
        this.vscale2.Adjustment.PageIncrement = 10;
        this.vscale2.Adjustment.StepIncrement = 1;
        this.vscale2.DrawValue = true;
        this.vscale2.Digits = 0;
        this.vscale2.ValuePos = ((Gtk.PositionType)(3));
        this.table3.Add(this.vscale2);
        Gtk.Table.TableChild w24 = ((Gtk.Table.TableChild)(this.table3[this.vscale2]));
        w24.TopAttach = ((uint)(1));
        w24.BottomAttach = ((uint)(2));
        w24.LeftAttach = ((uint)(1));
        w24.RightAttach = ((uint)(2));
        w24.XOptions = ((Gtk.AttachOptions)(4));
        // Container child table3.Gtk.Table+TableChild
        this.vscale3 = new Gtk.VScale(null);
        this.vscale3.CanFocus = true;
        this.vscale3.Name = "vscale3";
        this.vscale3.Inverted = true;
        this.vscale3.Adjustment.Upper = 228;
        this.vscale3.Adjustment.PageIncrement = 10;
        this.vscale3.Adjustment.StepIncrement = 1;
        this.vscale3.DrawValue = true;
        this.vscale3.Digits = 0;
        this.vscale3.ValuePos = ((Gtk.PositionType)(3));
        this.table3.Add(this.vscale3);
        Gtk.Table.TableChild w25 = ((Gtk.Table.TableChild)(this.table3[this.vscale3]));
        w25.TopAttach = ((uint)(1));
        w25.BottomAttach = ((uint)(2));
        w25.LeftAttach = ((uint)(2));
        w25.RightAttach = ((uint)(3));
        w25.XOptions = ((Gtk.AttachOptions)(4));
        // Container child table3.Gtk.Table+TableChild
        this.vscale4 = new Gtk.VScale(null);
        this.vscale4.CanFocus = true;
        this.vscale4.Name = "vscale4";
        this.vscale4.Inverted = true;
        this.vscale4.Adjustment.Upper = 228;
        this.vscale4.Adjustment.PageIncrement = 10;
        this.vscale4.Adjustment.StepIncrement = 1;
        this.vscale4.DrawValue = true;
        this.vscale4.Digits = 0;
        this.vscale4.ValuePos = ((Gtk.PositionType)(3));
        this.table3.Add(this.vscale4);
        Gtk.Table.TableChild w26 = ((Gtk.Table.TableChild)(this.table3[this.vscale4]));
        w26.TopAttach = ((uint)(1));
        w26.BottomAttach = ((uint)(2));
        w26.LeftAttach = ((uint)(3));
        w26.RightAttach = ((uint)(4));
        w26.XOptions = ((Gtk.AttachOptions)(4));
        // Container child table3.Gtk.Table+TableChild
        this.vscale5 = new Gtk.VScale(null);
        this.vscale5.CanFocus = true;
        this.vscale5.Name = "vscale5";
        this.vscale5.Inverted = true;
        this.vscale5.Adjustment.Upper = 228;
        this.vscale5.Adjustment.PageIncrement = 10;
        this.vscale5.Adjustment.StepIncrement = 1;
        this.vscale5.DrawValue = true;
        this.vscale5.Digits = 0;
        this.vscale5.ValuePos = ((Gtk.PositionType)(3));
        this.table3.Add(this.vscale5);
        Gtk.Table.TableChild w27 = ((Gtk.Table.TableChild)(this.table3[this.vscale5]));
        w27.TopAttach = ((uint)(1));
        w27.BottomAttach = ((uint)(2));
        w27.LeftAttach = ((uint)(4));
        w27.RightAttach = ((uint)(5));
        w27.XOptions = ((Gtk.AttachOptions)(4));
        // Container child table3.Gtk.Table+TableChild
        this.vscale6 = new Gtk.VScale(null);
        this.vscale6.CanFocus = true;
        this.vscale6.Name = "vscale6";
        this.vscale6.Inverted = true;
        this.vscale6.Adjustment.Upper = 228;
        this.vscale6.Adjustment.PageIncrement = 10;
        this.vscale6.Adjustment.StepIncrement = 1;
        this.vscale6.DrawValue = true;
        this.vscale6.Digits = 0;
        this.vscale6.ValuePos = ((Gtk.PositionType)(3));
        this.table3.Add(this.vscale6);
        Gtk.Table.TableChild w28 = ((Gtk.Table.TableChild)(this.table3[this.vscale6]));
        w28.TopAttach = ((uint)(1));
        w28.BottomAttach = ((uint)(2));
        w28.LeftAttach = ((uint)(5));
        w28.RightAttach = ((uint)(6));
        w28.XOptions = ((Gtk.AttachOptions)(4));
        this.vbox4.Add(this.table3);
        Gtk.Box.BoxChild w29 = ((Gtk.Box.BoxChild)(this.vbox4[this.table3]));
        w29.Position = 0;
        // Container child vbox4.Gtk.Box+BoxChild
        this.table2 = new Gtk.Table(((uint)(2)), ((uint)(3)), false);
        this.table2.Name = "table2";
        this.table2.RowSpacing = ((uint)(6));
        this.table2.ColumnSpacing = ((uint)(6));
        // Container child table2.Gtk.Table+TableChild
        this.button4 = new Gtk.Button();
        this.button4.CanFocus = true;
        this.button4.Name = "button4";
        this.button4.UseUnderline = true;
        this.button4.Label = Mono.Unix.Catalog.GetString("STEP UP");
        this.table2.Add(this.button4);
        Gtk.Table.TableChild w30 = ((Gtk.Table.TableChild)(this.table2[this.button4]));
        w30.XOptions = ((Gtk.AttachOptions)(4));
        w30.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table2.Gtk.Table+TableChild
        this.button5 = new Gtk.Button();
        this.button5.CanFocus = true;
        this.button5.Name = "button5";
        this.button5.UseUnderline = true;
        this.button5.Label = Mono.Unix.Catalog.GetString("STEP DOWN");
        this.table2.Add(this.button5);
        Gtk.Table.TableChild w31 = ((Gtk.Table.TableChild)(this.table2[this.button5]));
        w31.TopAttach = ((uint)(1));
        w31.BottomAttach = ((uint)(2));
        w31.XOptions = ((Gtk.AttachOptions)(4));
        w31.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table2.Gtk.Table+TableChild
        this.button6 = new Gtk.Button();
        this.button6.CanFocus = true;
        this.button6.Name = "button6";
        this.button6.UseUnderline = true;
        this.button6.Label = Mono.Unix.Catalog.GetString("TRIP");
        this.table2.Add(this.button6);
        Gtk.Table.TableChild w32 = ((Gtk.Table.TableChild)(this.table2[this.button6]));
        w32.TopAttach = ((uint)(1));
        w32.BottomAttach = ((uint)(2));
        w32.LeftAttach = ((uint)(2));
        w32.RightAttach = ((uint)(3));
        w32.XOptions = ((Gtk.AttachOptions)(4));
        w32.YOptions = ((Gtk.AttachOptions)(4));
        this.vbox4.Add(this.table2);
        Gtk.Box.BoxChild w33 = ((Gtk.Box.BoxChild)(this.vbox4[this.table2]));
        w33.Position = 1;
        w33.Expand = false;
        w33.Fill = false;
        this.hbox1.Add(this.vbox4);
        Gtk.Box.BoxChild w34 = ((Gtk.Box.BoxChild)(this.hbox1[this.vbox4]));
        w34.Position = 2;
        w34.Expand = false;
        w34.Fill = false;
        // Container child hbox1.Gtk.Box+BoxChild
        this.vseparator2 = new Gtk.VSeparator();
        this.vseparator2.Name = "vseparator2";
        this.hbox1.Add(this.vseparator2);
        Gtk.Box.BoxChild w35 = ((Gtk.Box.BoxChild)(this.hbox1[this.vseparator2]));
        w35.Position = 3;
        w35.Expand = false;
        w35.Fill = false;
        // Container child hbox1.Gtk.Box+BoxChild
        this.vbox2 = new Gtk.VBox();
        this.vbox2.Name = "vbox2";
        this.vbox2.Spacing = 6;
        // Container child vbox2.Gtk.Box+BoxChild
        this.label19 = new Gtk.Label();
        this.label19.Name = "label19";
        this.label19.LabelProp = Mono.Unix.Catalog.GetString("RCS makeup");
        this.vbox2.Add(this.label19);
        Gtk.Box.BoxChild w36 = ((Gtk.Box.BoxChild)(this.vbox2[this.label19]));
        w36.Position = 0;
        w36.Expand = false;
        w36.Fill = false;
        // Container child vbox2.Gtk.Box+BoxChild
        this.table4 = new Gtk.Table(((uint)(2)), ((uint)(3)), false);
        this.table4.Name = "table4";
        this.table4.RowSpacing = ((uint)(6));
        this.table4.ColumnSpacing = ((uint)(6));
        // Container child table4.Gtk.Table+TableChild
        this.label20 = new Gtk.Label();
        this.label20.Name = "label20";
        this.label20.LabelProp = Mono.Unix.Catalog.GetString("Water");
        this.table4.Add(this.label20);
        Gtk.Table.TableChild w37 = ((Gtk.Table.TableChild)(this.table4[this.label20]));
        w37.TopAttach = ((uint)(1));
        w37.BottomAttach = ((uint)(2));
        w37.XOptions = ((Gtk.AttachOptions)(4));
        w37.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table4.Gtk.Table+TableChild
        this.label21 = new Gtk.Label();
        this.label21.Name = "label21";
        this.label21.LabelProp = Mono.Unix.Catalog.GetString("liters");
        this.table4.Add(this.label21);
        Gtk.Table.TableChild w38 = ((Gtk.Table.TableChild)(this.table4[this.label21]));
        w38.LeftAttach = ((uint)(2));
        w38.RightAttach = ((uint)(3));
        w38.XOptions = ((Gtk.AttachOptions)(4));
        w38.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table4.Gtk.Table+TableChild
        this.label22 = new Gtk.Label();
        this.label22.Name = "label22";
        this.label22.LabelProp = Mono.Unix.Catalog.GetString("Boron");
        this.table4.Add(this.label22);
        Gtk.Table.TableChild w39 = ((Gtk.Table.TableChild)(this.table4[this.label22]));
        w39.XOptions = ((Gtk.AttachOptions)(4));
        w39.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table4.Gtk.Table+TableChild
        this.label23 = new Gtk.Label();
        this.label23.Name = "label23";
        this.label23.LabelProp = Mono.Unix.Catalog.GetString("liters");
        this.table4.Add(this.label23);
        Gtk.Table.TableChild w40 = ((Gtk.Table.TableChild)(this.table4[this.label23]));
        w40.TopAttach = ((uint)(1));
        w40.BottomAttach = ((uint)(2));
        w40.LeftAttach = ((uint)(2));
        w40.RightAttach = ((uint)(3));
        w40.XOptions = ((Gtk.AttachOptions)(4));
        w40.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table4.Gtk.Table+TableChild
        this.spinbutton1 = new Gtk.SpinButton(0, 1000, 1);
        this.spinbutton1.CanFocus = true;
        this.spinbutton1.Name = "spinbutton1";
        this.spinbutton1.Adjustment.PageIncrement = 10;
        this.spinbutton1.ClimbRate = 1;
        this.spinbutton1.Numeric = true;
        this.table4.Add(this.spinbutton1);
        Gtk.Table.TableChild w41 = ((Gtk.Table.TableChild)(this.table4[this.spinbutton1]));
        w41.LeftAttach = ((uint)(1));
        w41.RightAttach = ((uint)(2));
        w41.XOptions = ((Gtk.AttachOptions)(4));
        w41.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table4.Gtk.Table+TableChild
        this.spinbutton2 = new Gtk.SpinButton(0, 1000, 1);
        this.spinbutton2.CanFocus = true;
        this.spinbutton2.Name = "spinbutton2";
        this.spinbutton2.Adjustment.PageIncrement = 10;
        this.spinbutton2.ClimbRate = 1;
        this.spinbutton2.Numeric = true;
        this.table4.Add(this.spinbutton2);
        Gtk.Table.TableChild w42 = ((Gtk.Table.TableChild)(this.table4[this.spinbutton2]));
        w42.TopAttach = ((uint)(1));
        w42.BottomAttach = ((uint)(2));
        w42.LeftAttach = ((uint)(1));
        w42.RightAttach = ((uint)(2));
        w42.XOptions = ((Gtk.AttachOptions)(4));
        w42.YOptions = ((Gtk.AttachOptions)(4));
        this.vbox2.Add(this.table4);
        Gtk.Box.BoxChild w43 = ((Gtk.Box.BoxChild)(this.vbox2[this.table4]));
        w43.Position = 1;
        w43.Expand = false;
        w43.Fill = false;
        // Container child vbox2.Gtk.Box+BoxChild
        this.radiobutton1 = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("Borate"));
        this.radiobutton1.CanFocus = true;
        this.radiobutton1.Name = "radiobutton1";
        this.radiobutton1.DrawIndicator = true;
        this.radiobutton1.UseUnderline = true;
        this.radiobutton1.Group = new GLib.SList(System.IntPtr.Zero);
        this.vbox2.Add(this.radiobutton1);
        Gtk.Box.BoxChild w44 = ((Gtk.Box.BoxChild)(this.vbox2[this.radiobutton1]));
        w44.Position = 2;
        w44.Expand = false;
        w44.Fill = false;
        // Container child vbox2.Gtk.Box+BoxChild
        this.radiobutton2 = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("Dilute"));
        this.radiobutton2.CanFocus = true;
        this.radiobutton2.Name = "radiobutton2";
        this.radiobutton2.DrawIndicator = true;
        this.radiobutton2.UseUnderline = true;
        this.radiobutton2.Group = this.radiobutton1.Group;
        this.vbox2.Add(this.radiobutton2);
        Gtk.Box.BoxChild w45 = ((Gtk.Box.BoxChild)(this.vbox2[this.radiobutton2]));
        w45.Position = 3;
        w45.Expand = false;
        w45.Fill = false;
        // Container child vbox2.Gtk.Box+BoxChild
        this.togglebutton2 = new Gtk.ToggleButton();
        this.togglebutton2.CanFocus = true;
        this.togglebutton2.Name = "togglebutton2";
        this.togglebutton2.UseUnderline = true;
        this.togglebutton2.Label = Mono.Unix.Catalog.GetString("START");
        this.vbox2.Add(this.togglebutton2);
        Gtk.Box.BoxChild w46 = ((Gtk.Box.BoxChild)(this.vbox2[this.togglebutton2]));
        w46.Position = 4;
        w46.Expand = false;
        w46.Fill = false;
        this.hbox1.Add(this.vbox2);
        Gtk.Box.BoxChild w47 = ((Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
        w47.Position = 4;
        w47.Expand = false;
        w47.Fill = false;
        this.vbox1.Add(this.hbox1);
        Gtk.Box.BoxChild w48 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
        w48.Position = 1;
        // Container child vbox1.Gtk.Box+BoxChild
        this.statusbar1 = new Gtk.Statusbar();
        this.statusbar1.Name = "statusbar1";
        this.statusbar1.Spacing = 6;
        this.vbox1.Add(this.statusbar1);
        Gtk.Box.BoxChild w49 = ((Gtk.Box.BoxChild)(this.vbox1[this.statusbar1]));
        w49.Position = 2;
        w49.Expand = false;
        w49.Fill = false;
        this.Add(this.vbox1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 735;
        this.DefaultHeight = 409;
        this.Show();
        this.ExitAction.Activated += new System.EventHandler(this.OnExitActionActivated);
    }
}
