// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SimGUI {
    
    
    public partial class Turbine {
        
        private Gtk.VBox vbox2;
        
        private Gtk.Label label9;
        
        private Gtk.Label label10;
        
        private Gtk.Label label17;
        
        private Gtk.Table table5;
        
        private Gtk.Button button10;
        
        private Gtk.Button button7;
        
        private Gtk.Button button8;
        
        private Gtk.Button button9;
        
        private Gtk.Entry entry2;
        
        private Gtk.Entry entry3;
        
        private Gtk.Entry entry4;
        
        private Gtk.Label label11;
        
        private Gtk.Label label12;
        
        private Gtk.Label label13;
        
        private Gtk.Label label14;
        
        private Gtk.Label label15;
        
        private Gtk.Label label16;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget SimGUI.Turbine
            this.Name = "SimGUI.Turbine";
            this.Title = Mono.Unix.Catalog.GetString("Turbine");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Container child SimGUI.Turbine.Gtk.Container+ContainerChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.label9 = new Gtk.Label();
            this.label9.Name = "label9";
            this.label9.LabelProp = Mono.Unix.Catalog.GetString("Turbine power");
            this.vbox2.Add(this.label9);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox2[this.label9]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.label10 = new Gtk.Label();
            this.label10.Name = "label10";
            this.label10.LabelProp = Mono.Unix.Catalog.GetString("no data");
            this.vbox2.Add(this.label10);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox2[this.label10]));
            w2.Position = 1;
            w2.Expand = false;
            w2.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.label17 = new Gtk.Label();
            this.label17.Name = "label17";
            this.label17.LabelProp = Mono.Unix.Catalog.GetString("no data");
            this.vbox2.Add(this.label17);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox2[this.label17]));
            w3.Position = 2;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.table5 = new Gtk.Table(((uint)(5)), ((uint)(3)), false);
            this.table5.Name = "table5";
            this.table5.RowSpacing = ((uint)(6));
            this.table5.ColumnSpacing = ((uint)(6));
            // Container child table5.Gtk.Table+TableChild
            this.button10 = new Gtk.Button();
            this.button10.CanFocus = true;
            this.button10.Name = "button10";
            this.button10.UseUnderline = true;
            this.button10.Label = "HOLD";
            this.table5.Add(this.button10);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table5[this.button10]));
            w4.TopAttach = ((uint)(4));
            w4.BottomAttach = ((uint)(5));
            w4.LeftAttach = ((uint)(2));
            w4.RightAttach = ((uint)(3));
            w4.XOptions = ((Gtk.AttachOptions)(4));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.button7 = new Gtk.Button();
            this.button7.CanFocus = true;
            this.button7.Name = "button7";
            this.button7.UseUnderline = true;
            this.button7.Label = Mono.Unix.Catalog.GetString("GO");
            this.table5.Add(this.button7);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table5[this.button7]));
            w5.TopAttach = ((uint)(4));
            w5.BottomAttach = ((uint)(5));
            w5.LeftAttach = ((uint)(1));
            w5.RightAttach = ((uint)(2));
            w5.XOptions = ((Gtk.AttachOptions)(4));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.button8 = new Gtk.Button();
            this.button8.CanFocus = true;
            this.button8.Name = "button8";
            this.button8.UseUnderline = true;
            this.button8.Label = Mono.Unix.Catalog.GetString("SET");
            this.table5.Add(this.button8);
            Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.table5[this.button8]));
            w6.TopAttach = ((uint)(3));
            w6.BottomAttach = ((uint)(4));
            w6.LeftAttach = ((uint)(1));
            w6.RightAttach = ((uint)(2));
            w6.XOptions = ((Gtk.AttachOptions)(4));
            w6.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.button9 = new Gtk.Button();
            this.button9.CanFocus = true;
            this.button9.Name = "button9";
            this.button9.UseUnderline = true;
            this.button9.Label = Mono.Unix.Catalog.GetString("SET");
            this.table5.Add(this.button9);
            Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.table5[this.button9]));
            w7.TopAttach = ((uint)(3));
            w7.BottomAttach = ((uint)(4));
            w7.LeftAttach = ((uint)(2));
            w7.RightAttach = ((uint)(3));
            w7.XOptions = ((Gtk.AttachOptions)(4));
            w7.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.entry2 = new Gtk.Entry();
            this.entry2.CanFocus = true;
            this.entry2.Name = "entry2";
            this.entry2.IsEditable = true;
            this.entry2.InvisibleChar = '●';
            this.table5.Add(this.entry2);
            Gtk.Table.TableChild w8 = ((Gtk.Table.TableChild)(this.table5[this.entry2]));
            w8.TopAttach = ((uint)(2));
            w8.BottomAttach = ((uint)(3));
            w8.LeftAttach = ((uint)(1));
            w8.RightAttach = ((uint)(2));
            w8.XOptions = ((Gtk.AttachOptions)(4));
            w8.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.entry3 = new Gtk.Entry();
            this.entry3.CanFocus = true;
            this.entry3.Name = "entry3";
            this.entry3.IsEditable = true;
            this.entry3.InvisibleChar = '●';
            this.table5.Add(this.entry3);
            Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.table5[this.entry3]));
            w9.TopAttach = ((uint)(2));
            w9.BottomAttach = ((uint)(3));
            w9.XOptions = ((Gtk.AttachOptions)(4));
            w9.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.entry4 = new Gtk.Entry();
            this.entry4.CanFocus = true;
            this.entry4.Name = "entry4";
            this.entry4.IsEditable = true;
            this.entry4.InvisibleChar = '●';
            this.table5.Add(this.entry4);
            Gtk.Table.TableChild w10 = ((Gtk.Table.TableChild)(this.table5[this.entry4]));
            w10.TopAttach = ((uint)(2));
            w10.BottomAttach = ((uint)(3));
            w10.LeftAttach = ((uint)(2));
            w10.RightAttach = ((uint)(3));
            w10.XOptions = ((Gtk.AttachOptions)(4));
            w10.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.label11 = new Gtk.Label();
            this.label11.Name = "label11";
            this.label11.LabelProp = Mono.Unix.Catalog.GetString("no data");
            this.table5.Add(this.label11);
            Gtk.Table.TableChild w11 = ((Gtk.Table.TableChild)(this.table5[this.label11]));
            w11.TopAttach = ((uint)(1));
            w11.BottomAttach = ((uint)(2));
            w11.XOptions = ((Gtk.AttachOptions)(4));
            w11.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.label12 = new Gtk.Label();
            this.label12.Name = "label12";
            this.label12.LabelProp = Mono.Unix.Catalog.GetString("no data");
            this.table5.Add(this.label12);
            Gtk.Table.TableChild w12 = ((Gtk.Table.TableChild)(this.table5[this.label12]));
            w12.TopAttach = ((uint)(1));
            w12.BottomAttach = ((uint)(2));
            w12.LeftAttach = ((uint)(1));
            w12.RightAttach = ((uint)(2));
            w12.XOptions = ((Gtk.AttachOptions)(4));
            w12.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.label13 = new Gtk.Label();
            this.label13.Name = "label13";
            this.label13.LabelProp = Mono.Unix.Catalog.GetString("no data");
            this.table5.Add(this.label13);
            Gtk.Table.TableChild w13 = ((Gtk.Table.TableChild)(this.table5[this.label13]));
            w13.TopAttach = ((uint)(1));
            w13.BottomAttach = ((uint)(2));
            w13.LeftAttach = ((uint)(2));
            w13.RightAttach = ((uint)(3));
            w13.XOptions = ((Gtk.AttachOptions)(4));
            w13.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.label14 = new Gtk.Label();
            this.label14.Name = "label14";
            this.label14.LabelProp = Mono.Unix.Catalog.GetString("Current");
            this.table5.Add(this.label14);
            Gtk.Table.TableChild w14 = ((Gtk.Table.TableChild)(this.table5[this.label14]));
            w14.XOptions = ((Gtk.AttachOptions)(4));
            w14.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.label15 = new Gtk.Label();
            this.label15.Name = "label15";
            this.label15.LabelProp = Mono.Unix.Catalog.GetString("Target");
            this.table5.Add(this.label15);
            Gtk.Table.TableChild w15 = ((Gtk.Table.TableChild)(this.table5[this.label15]));
            w15.LeftAttach = ((uint)(1));
            w15.RightAttach = ((uint)(2));
            w15.XOptions = ((Gtk.AttachOptions)(4));
            w15.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.label16 = new Gtk.Label();
            this.label16.Name = "label16";
            this.label16.LabelProp = Mono.Unix.Catalog.GetString("Rate");
            this.table5.Add(this.label16);
            Gtk.Table.TableChild w16 = ((Gtk.Table.TableChild)(this.table5[this.label16]));
            w16.LeftAttach = ((uint)(2));
            w16.RightAttach = ((uint)(3));
            w16.XOptions = ((Gtk.AttachOptions)(4));
            w16.YOptions = ((Gtk.AttachOptions)(4));
            this.vbox2.Add(this.table5);
            Gtk.Box.BoxChild w17 = ((Gtk.Box.BoxChild)(this.vbox2[this.table5]));
            w17.Position = 3;
            w17.Expand = false;
            w17.Fill = false;
            this.Add(this.vbox2);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 501;
            this.DefaultHeight = 222;
            this.Show();
        }
    }
}
