
// This file has been generated by the GUI designer. Do not modify.
namespace SimGUI
{
	public partial class NewSimStarter
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget SimGUI.NewSimStarter
			this.Name = "SimGUI.NewSimStarter";
			this.Title = global::Mono.Unix.Catalog.GetString ("NewSimStarter");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
